export default {
  APP_STATUS: 'APP_STATUS',
  AUTH_USER: 'AUTH_USER',
  UNAUTH_USER: 'UNAUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',

  FETCH_BOARDS: 'FETCH_BOARDS',
  FETCH_VIDEOS: 'FETCH_VIDEOS',
  IMPORT_STORAGE: 'IMPORT_STORAGE',
  EMPTY_STORAGE: 'EMPTY_STORAGE',
  PUSH_STORAGE: 'PUSH_STORAGE',

  ADD_BOARD: 'ADD_BOARD',
  EDIT_BOARD: 'EDIT_BOARD',
  DELETE_BOARD: 'DELETE_BOARD',

  ADD_LIST: 'ADD_LIST',
  EDIT_LIST: 'EDIT_LIST',
  DELETE_LIST: 'DELETE_LIST',

  ADD_VIDEO: 'ADD_VIDEO',
  EDIT_VIDEO: 'EDIT_VIDEO',
  DELETE_VIDEO: 'DELETE_VIDEO'
}
